<?php

declare(strict_types=1);

namespace App\Modules\DynamicEntities\Services;

use App\Modules\AiAssistant\Contracts\LlmProviderInterface;
use App\Modules\AiAssistant\DTOs\LlmPrompt;
use App\Modules\AiAssistant\Services\AiPromptModuleService;
use App\Modules\DynamicEntities\Models\DynEntity;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/**
 * Natural-language → Report Builder definition using the tenant AI Assistant LLM.
 */
final class DynReportBuilderAiService
{
    public function __construct(
        private readonly LlmProviderInterface $llm,
        private readonly AiPromptModuleService $promptModules,
    ) {}

    /**
     * @param  array{
     *   prompt: string,
     *   entity_slug?: string|null,
     *   entity_hints?: list<string>|null,
     *   module_context?: string|null,
     *   preferred_model?: string|null
     * }  $input
     * @return array{definition: array<string, mixed>, source: string, model: string|null, notes: string|null}
     */
    public function build(array $input): array
    {
        $prompt = trim((string) ($input['prompt'] ?? ''));
        if ($prompt === '') {
            throw ValidationException::withMessages(['prompt' => ['Describe the report you want.']]);
        }

        $preferredEntity = trim((string) ($input['entity_slug'] ?? ''));
        $preferredModel = isset($input['preferred_model']) && is_string($input['preferred_model'])
            ? trim($input['preferred_model'])
            : '';
        $entityHints = [];
        if (is_array($input['entity_hints'] ?? null)) {
            foreach ($input['entity_hints'] as $hint) {
                if (is_string($hint) && trim($hint) !== '') {
                    $entityHints[] = trim($hint);
                }
            }
        }
        $moduleContext = isset($input['module_context']) && is_string($input['module_context'])
            ? trim($input['module_context'])
            : '';
        $catalog = $this->entityCatalog();

        if ($catalog === []) {
            throw ValidationException::withMessages([
                'prompt' => ['No active dynamic entities available to build a report from.'],
            ]);
        }

        $aiEnabled = (bool) config('ai_assistant.enabled', false);
        $provider = strtolower((string) config('ai_assistant.llm_provider', 'local'));
        // Cursor Cloud Agents is often too slow/unreliable for report-definition drafting — prefer heuristics.
        $useLlm = $aiEnabled && ! in_array($provider, ['local', 'fake', 'cursor', 'cursor_ai'], true);

        if ($useLlm) {
            try {
                $parsed = $this->buildViaLlm(
                    $prompt,
                    $preferredEntity,
                    $catalog,
                    $entityHints,
                    $moduleContext,
                    $preferredModel !== '' ? $preferredModel : null,
                );
                if ($parsed !== null) {
                    return [
                        'definition' => $parsed,
                        'source' => 'ai',
                        'model' => $preferredModel !== '' ? $preferredModel : $this->llm->modelName(),
                        'notes' => 'Generated by TowerOS AI Assistant. Review fields, then Run Preview.',
                    ];
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning('dynamic_entities.report_builder.ai_build_failed', [
                    'provider' => $provider,
                    'model' => $preferredModel !== '' ? $preferredModel : $this->llm->modelName(),
                    'error' => $e->getMessage(),
                ]);
                // Fall through to heuristics.
            }
        }

        $heuristic = $this->buildViaHeuristics($prompt, $preferredEntity, $catalog, $entityHints, $moduleContext);

        return [
            'definition' => $heuristic,
            'source' => $useLlm ? 'heuristic_fallback' : 'heuristic',
            'model' => $useLlm ? ($preferredModel !== '' ? $preferredModel : $this->llm->modelName()) : null,
            'notes' => $useLlm
                ? 'AI response could not be parsed; applied heuristic mapping. Name the Dynamic Entity or module (e.g. users, general_ledger) for a better match.'
                : (
                    in_array($provider, ['cursor', 'cursor_ai'], true)
                        ? 'Applied heuristic mapping (Cursor Agents is skipped for Report Builder). Switch AI_ASSISTANT_LLM_PROVIDER to gemini/openai for AI drafting, or name the entity in your prompt.'
                        : 'Applied heuristic mapping (AI provider is local/disabled). Name the entity/module in your prompt for better focus.'
                ),
        ];
    }

    /**
     * @param  list<array{slug: string, name: string, module_pack: string, fields: list<array{name: string, label: string, type: string}>}>  $catalog
     * @param  list<string>  $entityHints
     * @return array<string, mixed>|null
     */
    private function buildViaLlm(
        string $prompt,
        string $preferredEntity,
        array $catalog,
        array $entityHints = [],
        string $moduleContext = '',
        ?string $preferredModel = null,
    ): ?array {
        $catalogJson = json_encode($catalog, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if ($catalogJson === false) {
            return null;
        }

        $system = $this->promptModules->bodyForKey('reporting')."\n\n"
            ."# Report Builder JSON Schema\n"
            ."You convert a natural-language report request into a TowerOS Report Builder definition.\n"
            ."Reply with ONLY a single JSON object (no markdown, no commentary) matching:\n"
            ."{\n"
            ."  \"title\": string,\n"
            ."  \"caption\": string|null,\n"
            ."  \"entity_slug\": string (must be from catalog),\n"
            ."  \"format\": \"summary\"|\"detail\"|\"matrix\",\n"
            ."  \"metric\": \"count\"|\"sum\",\n"
            ."  \"metric_field\": string|null (required when metric=sum; must be a field name),\n"
            ."  \"group_by\": string|null,\n"
            ."  \"group_by_2\": string|null,\n"
            ."  \"matrix_column\": string|null,\n"
            ."  \"date_grouping\": \"exact\"|\"day\"|\"week\"|\"month\"|\"year\",\n"
            ."  \"chart\": \"bar\"|\"pie\"|\"line\"|\"none\",\n"
            ."  \"sort_by\": \"metric\"|\"group\",\n"
            ."  \"direction\": \"asc\"|\"desc\",\n"
            ."  \"row_limit\": number (1-2000),\n"
            ."  \"currency_prefix\": string|null,\n"
            ."  \"filters\": [{\"field\": string, \"op\": \"eq\", \"value\": string}]\n"
            ."}\n"
            ."Rules: only use entity_slug and field names from the catalog; "
            ."when the user asks for a dashboard / overview / full details / every record / all columns / 'not only' one field, set format=detail, chart=none, and leave group_by empty; "
            ."use summary+bar only when the user clearly wants totals grouped by a category (by status, by region, count of); "
            ."never group by unique identifiers like site_code/code/id for a dashboard of records; "
            ."use a short clean title (never paste the raw user question); "
            ."use sum only when a numeric amount-like field exists. "
            ."If the user names a module (Team & Access, Finance, Ticketing) or entity (tower sites), pick the matching entity_slug — never invent one.";

        $hintLine = $entityHints !== [] ? implode(', ', $entityHints) : 'none';
        $user = "Preferred entity (optional): ".($preferredEntity !== '' ? $preferredEntity : 'none')."\n"
            ."Entity hints: {$hintLine}\n"
            ."Module context: ".($moduleContext !== '' ? $moduleContext : 'none')."\n\n"
            ."Catalog:\n{$catalogJson}\n\n"
            ."Request:\n{$prompt}\n\n"
            ."Reply with ONLY the JSON object.";

        $result = $this->llm->complete(new LlmPrompt(
            system: $system,
            user: $user,
            pagePath: '/dynamic-entities/report-builder',
            moduleContext: 'reporting',
            modelOverride: $preferredModel,
        ));

        $decoded = $this->extractJsonObject($result->answer);
        if ($decoded === null) {
            \Illuminate\Support\Facades\Log::warning('dynamic_entities.report_builder.ai_json_unparsed', [
                'model' => $result->modelName,
                'answer_preview' => Str::limit($result->answer, 400, '…'),
            ]);

            return null;
        }

        return $this->normalizeDefinition($decoded, $catalog, $prompt, $preferredEntity, $entityHints, $moduleContext);
    }

    /**
     * @param  list<array{slug: string, name: string, module_pack: string, fields: list<array{name: string, label: string, type: string}>}>  $catalog
     * @param  list<string>  $entityHints
     * @return array<string, mixed>
     */
    private function buildViaHeuristics(
        string $prompt,
        string $preferredEntity,
        array $catalog,
        array $entityHints = [],
        string $moduleContext = '',
    ): array {
        $text = Str::lower($prompt);
        $entity = $this->pickEntity($text, $preferredEntity, $catalog, $entityHints, $moduleContext);

        $fieldNames = array_map(static fn (array $f): string => $f['name'], $entity['fields']);
        $wantsDetail = preg_match(
            '/\b(details?|full\s+details?|every\s+record|line\s+items?|list\s+of|all\s+columns|full\s+list|not\s+only|overview|inventory)\b/',
            $text,
        ) === 1;
        // "Create dashboard for tower sites" = record listing / operational board, not count-by-code.
        $wantsDashboardListing = preg_match('/\b(dashboard|board)\b/', $text) === 1
            && preg_match('/\b(by\s+\w+|grouped?\s+by|count\s+of|totals?\s+by|pie|bar\s+chart)\b/', $text) !== 1;

        $format = 'summary';
        if (preg_match('/\b(matrix|cross[- ]?tab|pivot)\b/', $text) === 1) {
            $format = 'matrix';
        } elseif ($wantsDetail || $wantsDashboardListing) {
            $format = 'detail';
        }

        $metric = preg_match('/\b(sum|total amount|amount by|total po)\b/', $text) === 1 ? 'sum' : 'count';
        $metricField = null;
        if ($metric === 'sum') {
            foreach ($fieldNames as $name) {
                if (preg_match('/amount|total|price|cost|value|balance/', $name) === 1) {
                    $metricField = $name;
                    break;
                }
            }
        }

        $chart = $format === 'detail' ? 'none' : 'bar';
        if (preg_match('/\bpie\b/', $text) === 1) {
            $chart = 'pie';
        } elseif (preg_match('/\b(line\s+chart|line)\b/', $text) === 1 && preg_match('/\bchart\b/', $text) === 1) {
            $chart = 'line';
        } elseif (preg_match('/\bbar\s+chart\b|\bwith\s+bar\b|\bbar\s+graph\b/', $text) === 1) {
            $chart = 'bar';
            // A dashboard "with bar chart" is usually a category summary, not a raw listing.
            if ($wantsDashboardListing && preg_match('/\b(by\s+\w+|grouped?\s+by)\b/', $text) !== 1) {
                $format = 'summary';
            }
        } elseif (preg_match('/\b(table|no chart)\b/', $text) === 1) {
            $chart = 'none';
        }

        $dateGrouping = 'exact';
        if (preg_match('/\b(this year|by year|yearly)\b/', $text) === 1) {
            $dateGrouping = 'year';
        } elseif (preg_match('/\b(this month|by month|monthly)\b/', $text) === 1) {
            $dateGrouping = 'month';
        } elseif (preg_match('/\b(weekly|by week)\b/', $text) === 1) {
            $dateGrouping = 'week';
        }

        // Detail / dashboard listings should not collapse to a single group key unless explicitly asked.
        $groupBy = null;
        if ($format !== 'detail') {
            foreach ($fieldNames as $name) {
                if ($this->isUniqueIdentifierField($name)) {
                    continue;
                }
                $plain = str_replace('_', ' ', $name);
                if (str_contains($text, $plain) || str_contains($text, $name)) {
                    $groupBy = $name;
                    break;
                }
            }
            if ($groupBy === null) {
                foreach ($fieldNames as $name) {
                    if (preg_match('/^(category|status|type|region|warehouse|vendor|department|customer|role)$/', $name) === 1) {
                        $groupBy = $name;
                        break;
                    }
                }
            }
            if ($groupBy === null && in_array('status', $fieldNames, true)) {
                $groupBy = 'status';
            }
        }

        return $this->normalizeDefinition([
            'title' => $this->humanTitle($prompt, $entity['name'], $format),
            'caption' => null,
            'entity_slug' => $entity['slug'],
            'format' => $format,
            'metric' => $metric,
            'metric_field' => $metricField,
            'group_by' => $groupBy,
            'group_by_2' => null,
            'matrix_column' => null,
            'date_grouping' => $dateGrouping,
            'chart' => $chart,
            'sort_by' => 'metric',
            'direction' => 'desc',
            'row_limit' => $format === 'detail' ? 1000 : 500,
            'currency_prefix' => preg_match('/\b(peso|php|₱)\b/i', $prompt) === 1 ? '₱' : null,
            'filters' => $this->heuristicFilters($prompt, $fieldNames),
        ], $catalog, $prompt, $preferredEntity, $entityHints, $moduleContext);
    }

    /**
     * @param  list<string>  $fieldNames
     * @return list<array{field: string, op: string, value: string}>
     */
    private function heuristicFilters(string $prompt, array $fieldNames): array
    {
        $filters = [];
        $text = Str::lower($prompt);

        // Prefer SCREAMING_SNAKE tokens from the original prompt (e.g. TANZA_CAVITE).
        $value = null;
        if (preg_match('/\b([A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+)\b/', $prompt, $m) === 1
            && preg_match('/\b(only|filter|equals?)\b/i', $prompt) === 1
        ) {
            $value = $m[1];
        } elseif (preg_match('/\b(?:all\s+)?([a-z0-9][a-z0-9_]{2,})\s+only\b/u', $text, $m) === 1
            || preg_match('/\bonly\s+([a-z0-9][a-z0-9_]{2,})\b/u', $text, $m) === 1
            || preg_match('/\b(?:filter(?:ed)?\s+(?:to|for|by)|equals?)\s+([a-z0-9][a-z0-9_]{2,})\b/u', $text, $m) === 1
        ) {
            $value = strtoupper((string) $m[1]);
        }

        if ($value !== null && $value !== '' && ! in_array(strtolower($value), ['sites', 'tower', 'dashboard', 'report', 'records'], true)) {
            $field = null;
            foreach (['municipality', 'location', 'region', 'area', 'province', 'city', 'status', 'site_code'] as $candidate) {
                if (in_array($candidate, $fieldNames, true)) {
                    $field = $candidate;
                    break;
                }
            }
            if ($field !== null) {
                $filters[] = ['field' => $field, 'op' => 'eq', 'value' => $value];
            }
        }

        return $filters;
    }

    private function isUniqueIdentifierField(string $name): bool
    {
        return preg_match('/^(id|uuid|slug|code|site_code|ticket_number|invoice_no|reference)$/', $name) === 1
            || str_ends_with($name, '_code')
            || str_ends_with($name, '_id');
    }

    private function humanTitle(string $prompt, string $entityName, string $format): string
    {
        $cleaned = trim(preg_replace('/\s+/', ' ', $prompt) ?? $prompt);
        $cleaned = preg_replace('/^(can you|could you|please|pls|i want to|i need to|make|create|build|generate)\s+/i', '', $cleaned) ?? $cleaned;
        $cleaned = rtrim($cleaned, " \t\n\r\0\x0B?");
        $cleaned = trim($cleaned);

        $looksLikeRawQuestion = $cleaned === ''
            || strlen($cleaned) > 90
            || preg_match('/\?/', $prompt) === 1
            || preg_match('/\b(mkae|teh|adn)\b/i', $cleaned) === 1
            || preg_match('/^(full details?|details? of)\b/i', $cleaned) === 1;

        if ($looksLikeRawQuestion || preg_match('/\b(dashboard|board)\b/i', $cleaned) === 1) {
            $suffix = match ($format) {
                'detail' => preg_match('/\b(dashboard|board)\b/i', $cleaned) === 1 ? 'Dashboard' : 'Full details',
                'matrix' => 'Matrix',
                default => 'Summary',
            };

            return trim($entityName !== '' ? $entityName.' — '.$suffix : $suffix);
        }

        return Str::limit(Str::title($cleaned), 100, '');
    }

    /**
     * @param  list<array{slug: string, name: string, module_pack: string, fields: list<array{name: string, label: string, type: string}>}>  $catalog
     * @param  list<string>  $entityHints
     * @return array{slug: string, name: string, module_pack: string, fields: list<array{name: string, label: string, type: string}>}
     */
    private function pickEntity(
        string $text,
        string $preferredEntity,
        array $catalog,
        array $entityHints = [],
        string $moduleContext = '',
    ): array {
        $bySlug = [];
        foreach ($catalog as $row) {
            $bySlug[$row['slug']] = $row;
        }

        if ($preferredEntity !== '' && isset($bySlug[$preferredEntity])) {
            return $bySlug[$preferredEntity];
        }

        foreach ($entityHints as $hint) {
            if (isset($bySlug[$hint])) {
                return $bySlug[$hint];
            }
        }

        foreach ($this->aliasHintsForPrompt($text, $moduleContext) as $hint) {
            if (isset($bySlug[$hint])) {
                return $bySlug[$hint];
            }
        }

        $best = null;
        $bestScore = 0;
        foreach ($catalog as $row) {
            $score = $this->scoreEntityMatch($text, $row, $moduleContext);
            if ($score > $bestScore) {
                $bestScore = $score;
                $best = $row;
            }
        }

        return $best ?? $catalog[0];
    }

    /**
     * @return list<string>
     */
    private function aliasHintsForPrompt(string $text, string $moduleContext): array
    {
        $hints = [];

        $aliasGroups = [
            ['needles' => ['team & access', 'team and access', 'workspace users', 'all users', 'tenant users'], 'slugs' => ['users', 'users_system', 'tenant_users']],
            ['needles' => ['general ledger', 'gl report', 'gl dashboard'], 'slugs' => ['general_ledger', 'gl']],
            ['needles' => ['chart of accounts', 'coa'], 'slugs' => ['chart_of_accounts']],
            ['needles' => ['purchase order', 'po report'], 'slugs' => ['purchase_orders', 'purchase_order']],
            ['needles' => ['ticket', 'ticketing'], 'slugs' => ['tickets', 'site_tickets']],
            ['needles' => ['tower sites', 'tower site', 'sites inventory', 'site master'], 'slugs' => ['tower_sites', 'sites', 'site']],
        ];

        foreach ($aliasGroups as $group) {
            foreach ($group['needles'] as $needle) {
                if (str_contains($text, $needle)) {
                    foreach ($group['slugs'] as $slug) {
                        $hints[] = $slug;
                    }
                    break;
                }
            }
        }

        if (preg_match('/\busers?\b/', $text) === 1) {
            array_unshift($hints, 'users', 'users_system', 'tenant_users');
        }

        if ($moduleContext === 'team_access') {
            array_unshift($hints, 'users', 'users_system', 'tenant_users');
        }

        return array_values(array_unique($hints));
    }

    /**
     * @param  array{slug: string, name: string, module_pack: string, fields: list<array{name: string, label: string, type: string}>}  $row
     */
    private function scoreEntityMatch(string $text, array $row, string $moduleContext): int
    {
        $score = 0;
        $slug = Str::lower($row['slug']);
        $name = Str::lower($row['name']);
        $slugWords = str_replace('_', ' ', $slug);

        if (str_contains($text, $slug)) {
            $score += 100;
        }
        if ($slugWords !== '' && str_contains($text, $slugWords)) {
            $score += 80;
        }
        if ($name !== '' && str_contains($text, $name)) {
            $score += 80;
        }

        foreach (preg_split('/[_\s]+/', $slug) ?: [] as $word) {
            if (strlen($word) >= 4 && preg_match('/\b'.preg_quote($word, '/').'\b/', $text) === 1) {
                $score += 25;
            }
        }

        if ($moduleContext === 'team_access' && str_contains($slug, 'user')) {
            $score += 40;
        }
        if ($moduleContext === 'ticketing' && (str_contains($slug, 'ticket') || $row['module_pack'] === 'ticketing')) {
            $score += 40;
        }
        if (in_array($moduleContext, ['dynamic_entities', 'reporting', 'html_reports'], true) && $row['module_pack'] === 'finance') {
            // Mild bias only when finance words appear.
            if (preg_match('/\b(finance|ledger|invoice|account)\b/', $text) === 1) {
                $score += 15;
            }
        }

        return $score;
    }

    /**
     * @param  array<string, mixed>  $raw
     * @param  list<array{slug: string, name: string, module_pack: string, fields: list<array{name: string, label: string, type: string}>}>  $catalog
     * @param  list<string>  $entityHints
     * @return array<string, mixed>
     */
    private function normalizeDefinition(
        array $raw,
        array $catalog,
        string $fallbackTitle,
        string $preferredEntity = '',
        array $entityHints = [],
        string $moduleContext = '',
    ): array {
        $bySlug = [];
        foreach ($catalog as $row) {
            $bySlug[$row['slug']] = $row;
        }

        $entitySlug = trim((string) ($raw['entity_slug'] ?? ''));
        if ($entitySlug === '' || ! isset($bySlug[$entitySlug])) {
            $entitySlug = $this->pickEntity(
                Str::lower($fallbackTitle),
                $preferredEntity,
                $catalog,
                $entityHints,
                $moduleContext,
            )['slug'];
        }
        $entity = $bySlug[$entitySlug];
        $allowedFields = array_values(array_unique(array_merge(
            ['status', 'title', 'created_at', 'updated_at'],
            array_map(static fn (array $f): string => $f['name'], $entity['fields']),
        )));

        $pickField = static function (mixed $value) use ($allowedFields): ?string {
            $name = trim((string) ($value ?? ''));
            if ($name === '') {
                return null;
            }
            if (in_array($name, $allowedFields, true)) {
                return $name;
            }
            foreach ($allowedFields as $allowed) {
                if (strcasecmp($allowed, $name) === 0) {
                    return $allowed;
                }
            }

            return null;
        };

        $format = strtolower((string) ($raw['format'] ?? 'summary'));
        if (! in_array($format, ['summary', 'detail', 'matrix'], true)) {
            $format = 'summary';
        }
        $metric = strtolower((string) ($raw['metric'] ?? 'count'));
        if (! in_array($metric, ['count', 'sum'], true)) {
            $metric = 'count';
        }
        $metricField = $pickField($raw['metric_field'] ?? null);
        if ($metric === 'sum' && $metricField === null) {
            $metric = 'count';
        }

        $chart = strtolower((string) ($raw['chart'] ?? 'bar'));
        if (! in_array($chart, ['bar', 'pie', 'line', 'none'], true)) {
            $chart = 'bar';
        }
        $dateGrouping = strtolower((string) ($raw['date_grouping'] ?? 'exact'));
        if (! in_array($dateGrouping, ['exact', 'day', 'week', 'month', 'year'], true)) {
            $dateGrouping = 'exact';
        }
        $sortBy = strtolower((string) ($raw['sort_by'] ?? 'metric'));
        if (! in_array($sortBy, ['metric', 'group'], true)) {
            $sortBy = 'metric';
        }
        $direction = strtolower((string) ($raw['direction'] ?? 'desc')) === 'asc' ? 'asc' : 'desc';
        $rowLimit = max(1, min(2000, (int) ($raw['row_limit'] ?? 500)));

        $filters = [];
        if (is_array($raw['filters'] ?? null)) {
            foreach ($raw['filters'] as $f) {
                if (! is_array($f)) {
                    continue;
                }
                $field = $pickField($f['field'] ?? null);
                $value = trim((string) ($f['value'] ?? ''));
                if ($field === null || $value === '') {
                    continue;
                }
                $filters[] = [
                    'field' => $field,
                    'op' => 'eq',
                    'value' => $value,
                ];
            }
        }

        $title = trim((string) ($raw['title'] ?? ''));
        if ($title === '' || $this->looksLikeRawPromptTitle($title, $fallbackTitle)) {
            $title = $this->humanTitle($fallbackTitle, (string) $entity['name'], $format);
        }

        $groupBy = $pickField($raw['group_by'] ?? null);
        $groupBy2 = $pickField($raw['group_by_2'] ?? null);
        $matrixColumn = $pickField($raw['matrix_column'] ?? $raw['group_by_2'] ?? null);

        // Detail listings should not collapse to a single group key unless explicitly asked.
        if ($format === 'detail' && $this->wantsUngroupedDetail($fallbackTitle)) {
            $groupBy = null;
            if ($chart !== 'none' && ! preg_match('/\b(pie|bar|line)\s+chart\b/i', $fallbackTitle)) {
                $chart = 'none';
            }
        }

        // Dashboard / overview without explicit "by X" → detail listing even if LLM said summary.
        if ($this->wantsDashboardListing($fallbackTitle) && $format === 'summary') {
            $format = 'detail';
            $groupBy = null;
            if ($chart !== 'none' && ! preg_match('/\b(pie|bar|line)\s+chart\b/i', $fallbackTitle)) {
                $chart = 'none';
            }
            if ($title === '' || $this->looksLikeRawPromptTitle($title, $fallbackTitle) || preg_match('/\bdashboard\b/i', $title) === 1) {
                $title = $this->humanTitle($fallbackTitle, (string) $entity['name'], $format);
            }
        }

        return [
            'title' => $title,
            'caption' => trim((string) ($raw['caption'] ?? '')) ?: null,
            'entity_slug' => $entitySlug,
            'format' => $format,
            'metric' => $metric,
            'metric_field' => $metricField ?? '',
            'group_by' => $groupBy ?? '',
            'group_by_2' => $groupBy2 ?? '',
            'matrix_column' => $matrixColumn ?? '',
            'date_grouping' => $dateGrouping,
            'chart' => $chart,
            'sort_by' => $sortBy,
            'direction' => $direction,
            'row_limit' => $rowLimit,
            'currency_prefix' => trim((string) ($raw['currency_prefix'] ?? '')),
            'filters' => $filters,
        ];
    }

    /**
     * @return array<string, mixed>|null
     */
    private function extractJsonObject(string $answer): ?array
    {
        $text = trim($answer);
        if ($text === '') {
            return null;
        }

        if (preg_match('/```(?:json)?\s*([\s\S]*?)```/i', $text, $m) === 1) {
            $text = trim($m[1]);
        }

        $start = strpos($text, '{');
        if ($start === false) {
            return null;
        }

        $depth = 0;
        $inString = false;
        $escape = false;
        $end = null;
        $length = strlen($text);
        for ($i = $start; $i < $length; $i++) {
            $ch = $text[$i];
            if ($inString) {
                if ($escape) {
                    $escape = false;
                    continue;
                }
                if ($ch === '\\') {
                    $escape = true;
                    continue;
                }
                if ($ch === '"') {
                    $inString = false;
                }
                continue;
            }

            if ($ch === '"') {
                $inString = true;
                continue;
            }
            if ($ch === '{') {
                $depth++;
            } elseif ($ch === '}') {
                $depth--;
                if ($depth === 0) {
                    $end = $i;
                    break;
                }
            }
        }

        if ($end === null) {
            return null;
        }

        $json = substr($text, $start, $end - $start + 1);
        $decoded = json_decode($json, true);
        if (is_array($decoded)) {
            return $decoded;
        }

        // Tolerate trailing commas common in LLM JSON.
        $cleaned = preg_replace('/,\s*([}\]])/', '$1', $json);
        $decoded = is_string($cleaned) ? json_decode($cleaned, true) : null;

        return is_array($decoded) ? $decoded : null;
    }

    private function looksLikeRawPromptTitle(string $title, string $fallbackTitle): bool
    {
        $a = Str::lower(trim($title));
        $b = Str::lower(trim($fallbackTitle));
        if ($a === '' || $b === '') {
            return false;
        }
        if ($a === $b) {
            return true;
        }
        if (preg_match('/\?/', $title) === 1) {
            return true;
        }
        if (preg_match('/^(can you|could you|please|make|create|build|generate)\b/i', $title) === 1) {
            return true;
        }

        return preg_match('/\b(mkae|teh|adn)\b/i', $title) === 1;
    }

    private function wantsUngroupedDetail(string $prompt): bool
    {
        $text = Str::lower($prompt);

        return preg_match(
            '/\b(details?|full\s+details?|every\s+record|line\s+items?|list\s+of|all\s+columns|full\s+list|not\s+only|overview|inventory|dashboard|board)\b/',
            $text,
        ) === 1;
    }

    private function wantsDashboardListing(string $prompt): bool
    {
        $text = Str::lower($prompt);

        return preg_match('/\b(dashboard|board|overview)\b/', $text) === 1
            && preg_match('/\b(by\s+\w+|grouped?\s+by|count\s+of|totals?\s+by|pie|bar\s+chart)\b/', $text) !== 1;
    }

    /**
     * @return list<array{slug: string, name: string, module_pack: string, fields: list<array{name: string, label: string, type: string}>}>
     */
    private function entityCatalog(): array
    {
        $entities = DynEntity::query()
            ->where('is_active', true)
            ->with(['fields' => static function ($q): void {
                $q->orderBy('field_order');
            }])
            ->orderBy('sort_order')
            ->orderBy('name')
            ->limit(80)
            ->get();

        $out = [];
        foreach ($entities as $entity) {
            $fields = [];
            foreach ($entity->fields as $field) {
                if ($field->is_system_field || in_array($field->name, ['actions', 'workflows', 'print', 'id'], true)) {
                    continue;
                }
                $fields[] = [
                    'name' => (string) $field->name,
                    'label' => (string) ($field->label ?: $field->name),
                    'type' => (string) $field->type,
                ];
                if (count($fields) >= 40) {
                    break;
                }
            }
            $out[] = [
                'slug' => (string) $entity->slug,
                'name' => (string) $entity->name,
                'module_pack' => (string) ($entity->module_pack ?? ''),
                'fields' => $fields,
            ];
        }

        return $out;
    }
}
