<?php

declare(strict_types=1);

namespace App\Modules\DynamicEntities\Services;

use App\Modules\AiAssistant\Contracts\LlmProviderInterface;
use App\Modules\AiAssistant\DTOs\LlmPrompt;
use App\Modules\AiAssistant\Services\AiPromptModuleService;
use App\Modules\DynamicEntities\Models\DynEntity;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/**
 * Natural-language → Report Builder definition using the tenant AI Assistant LLM.
 */
final class DynReportBuilderAiService
{
    public function __construct(
        private readonly LlmProviderInterface $llm,
        private readonly AiPromptModuleService $promptModules,
    ) {}

    /**
     * @param  array{prompt: string, entity_slug?: string|null}  $input
     * @return array{definition: array<string, mixed>, source: string, model: string|null, notes: string|null}
     */
    public function build(array $input): array
    {
        $prompt = trim((string) ($input['prompt'] ?? ''));
        if ($prompt === '') {
            throw ValidationException::withMessages(['prompt' => ['Describe the report you want.']]);
        }

        $preferredEntity = trim((string) ($input['entity_slug'] ?? ''));
        $catalog = $this->entityCatalog();

        if ($catalog === []) {
            throw ValidationException::withMessages([
                'prompt' => ['No active dynamic entities available to build a report from.'],
            ]);
        }

        $aiEnabled = (bool) config('ai_assistant.enabled', false);
        $provider = strtolower((string) config('ai_assistant.llm_provider', 'local'));
        $useLlm = $aiEnabled && ! in_array($provider, ['local', 'fake'], true);

        if ($useLlm) {
            try {
                $parsed = $this->buildViaLlm($prompt, $preferredEntity, $catalog);
                if ($parsed !== null) {
                    return [
                        'definition' => $parsed,
                        'source' => 'ai',
                        'model' => $this->llm->modelName(),
                        'notes' => 'Generated by TowerOS AI Assistant. Review fields, then Run Preview.',
                    ];
                }
            } catch (\Throwable) {
                // Fall through to heuristics.
            }
        }

        $heuristic = $this->buildViaHeuristics($prompt, $preferredEntity, $catalog);

        return [
            'definition' => $heuristic,
            'source' => $useLlm ? 'heuristic_fallback' : 'heuristic',
            'model' => $useLlm ? $this->llm->modelName() : null,
            'notes' => $useLlm
                ? 'AI response could not be parsed; applied heuristic mapping. Configure OPENAI/Bedrock/Cursor for better results.'
                : 'Applied heuristic mapping (AI provider is local/disabled). Set AI_ASSISTANT_LLM_PROVIDER=openai (or bedrock/cursor) for LLM builds.',
        ];
    }

    /**
     * @param  list<array{slug: string, name: string, fields: list<array{name: string, label: string, type: string}>}>  $catalog
     * @return array<string, mixed>|null
     */
    private function buildViaLlm(string $prompt, string $preferredEntity, array $catalog): ?array
    {
        $catalogJson = json_encode($catalog, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if ($catalogJson === false) {
            return null;
        }

        $system = $this->promptModules->bodyForKey('reporting')."\n\n"
            ."# Report Builder JSON Schema\n"
            ."You convert a natural-language report request into a TowerOS Report Builder definition.\n"
            ."Reply with ONLY a single JSON object (no markdown, no commentary) matching:\n"
            ."{\n"
            ."  \"title\": string,\n"
            ."  \"caption\": string|null,\n"
            ."  \"entity_slug\": string (must be from catalog),\n"
            ."  \"format\": \"summary\"|\"detail\"|\"matrix\",\n"
            ."  \"metric\": \"count\"|\"sum\",\n"
            ."  \"metric_field\": string|null (required when metric=sum; must be a field name),\n"
            ."  \"group_by\": string|null,\n"
            ."  \"group_by_2\": string|null,\n"
            ."  \"matrix_column\": string|null,\n"
            ."  \"date_grouping\": \"exact\"|\"day\"|\"week\"|\"month\"|\"year\",\n"
            ."  \"chart\": \"bar\"|\"pie\"|\"line\"|\"none\",\n"
            ."  \"sort_by\": \"metric\"|\"group\",\n"
            ."  \"direction\": \"asc\"|\"desc\",\n"
            ."  \"row_limit\": number (1-2000),\n"
            ."  \"currency_prefix\": string|null,\n"
            ."  \"filters\": [{\"field\": string, \"op\": \"eq\", \"value\": string}]\n"
            ."}\n"
            ."Rules: only use entity_slug and field names from the catalog; prefer summary+bar for totals-by-group; "
            ."use sum only when a numeric amount-like field exists.";

        $user = "Preferred entity (optional): ".($preferredEntity !== '' ? $preferredEntity : 'none')."\n\n"
            ."Catalog:\n{$catalogJson}\n\n"
            ."Request:\n{$prompt}";

        $result = $this->llm->complete(new LlmPrompt(
            system: $system,
            user: $user,
            pagePath: '/dynamic-entities/report-builder',
            moduleContext: 'reporting',
        ));

        $decoded = $this->extractJsonObject($result->answer);
        if ($decoded === null) {
            return null;
        }

        return $this->normalizeDefinition($decoded, $catalog, $prompt);
    }

    /**
     * @param  list<array{slug: string, name: string, fields: list<array{name: string, label: string, type: string}>}>  $catalog
     * @return array<string, mixed>
     */
    private function buildViaHeuristics(string $prompt, string $preferredEntity, array $catalog): array
    {
        $text = Str::lower($prompt);
        $entity = null;
        if ($preferredEntity !== '') {
            foreach ($catalog as $row) {
                if ($row['slug'] === $preferredEntity) {
                    $entity = $row;
                    break;
                }
            }
        }
        if ($entity === null) {
            foreach ($catalog as $row) {
                $slugWords = str_replace('_', ' ', $row['slug']);
                if (str_contains($text, $row['slug']) || str_contains($text, $slugWords) || str_contains($text, Str::lower($row['name']))) {
                    $entity = $row;
                    break;
                }
            }
        }
        $entity ??= $catalog[0];

        $fieldNames = array_map(static fn (array $f): string => $f['name'], $entity['fields']);
        $format = 'summary';
        if (preg_match('/\b(matrix|cross[- ]?tab|pivot)\b/', $text) === 1) {
            $format = 'matrix';
        } elseif (preg_match('/\b(detail|every record|line item|list of)\b/', $text) === 1) {
            $format = 'detail';
        }

        $metric = preg_match('/\b(sum|total amount|amount by|total po)\b/', $text) === 1 ? 'sum' : 'count';
        $metricField = null;
        if ($metric === 'sum') {
            foreach ($fieldNames as $name) {
                if (preg_match('/amount|total|price|cost|value|balance/', $name) === 1) {
                    $metricField = $name;
                    break;
                }
            }
        }

        $chart = 'bar';
        if (preg_match('/\bpie\b/', $text) === 1) {
            $chart = 'pie';
        } elseif (preg_match('/\bline\b/', $text) === 1) {
            $chart = 'line';
        } elseif (preg_match('/\b(table|no chart)\b/', $text) === 1) {
            $chart = 'none';
        }

        $dateGrouping = 'exact';
        if (preg_match('/\b(this year|by year|yearly)\b/', $text) === 1) {
            $dateGrouping = 'year';
        } elseif (preg_match('/\b(this month|by month|monthly)\b/', $text) === 1) {
            $dateGrouping = 'month';
        } elseif (preg_match('/\b(weekly|by week)\b/', $text) === 1) {
            $dateGrouping = 'week';
        }

        $groupBy = null;
        foreach ($fieldNames as $name) {
            if (str_contains($text, str_replace('_', ' ', $name)) || str_contains($text, $name)) {
                $groupBy = $name;
                break;
            }
        }
        if ($groupBy === null) {
            foreach ($fieldNames as $name) {
                if (preg_match('/category|status|type|warehouse|tower|site|vendor|department|customer/', $name) === 1) {
                    $groupBy = $name;
                    break;
                }
            }
        }
        if ($groupBy === null && in_array('status', $fieldNames, true)) {
            $groupBy = 'status';
        }

        return $this->normalizeDefinition([
            'title' => Str::limit($prompt, 120, ''),
            'caption' => null,
            'entity_slug' => $entity['slug'],
            'format' => $format,
            'metric' => $metric,
            'metric_field' => $metricField,
            'group_by' => $groupBy,
            'group_by_2' => null,
            'matrix_column' => null,
            'date_grouping' => $dateGrouping,
            'chart' => $chart,
            'sort_by' => 'metric',
            'direction' => 'desc',
            'row_limit' => 500,
            'currency_prefix' => preg_match('/\b(peso|php|₱)\b/i', $prompt) === 1 ? '₱' : null,
            'filters' => [],
        ], $catalog, $prompt);
    }

    /**
     * @param  array<string, mixed>  $raw
     * @param  list<array{slug: string, name: string, fields: list<array{name: string, label: string, type: string}>}>  $catalog
     * @return array<string, mixed>
     */
    private function normalizeDefinition(array $raw, array $catalog, string $fallbackTitle): array
    {
        $bySlug = [];
        foreach ($catalog as $row) {
            $bySlug[$row['slug']] = $row;
        }

        $entitySlug = trim((string) ($raw['entity_slug'] ?? ''));
        if ($entitySlug === '' || ! isset($bySlug[$entitySlug])) {
            $entitySlug = $catalog[0]['slug'];
        }
        $entity = $bySlug[$entitySlug];
        $allowedFields = array_values(array_unique(array_merge(
            ['status', 'title', 'created_at', 'updated_at'],
            array_map(static fn (array $f): string => $f['name'], $entity['fields']),
        )));

        $pickField = static function (mixed $value) use ($allowedFields): ?string {
            $name = trim((string) ($value ?? ''));
            if ($name === '') {
                return null;
            }
            if (in_array($name, $allowedFields, true)) {
                return $name;
            }
            foreach ($allowedFields as $allowed) {
                if (strcasecmp($allowed, $name) === 0) {
                    return $allowed;
                }
            }

            return null;
        };

        $format = strtolower((string) ($raw['format'] ?? 'summary'));
        if (! in_array($format, ['summary', 'detail', 'matrix'], true)) {
            $format = 'summary';
        }
        $metric = strtolower((string) ($raw['metric'] ?? 'count'));
        if (! in_array($metric, ['count', 'sum'], true)) {
            $metric = 'count';
        }
        $metricField = $pickField($raw['metric_field'] ?? null);
        if ($metric === 'sum' && $metricField === null) {
            $metric = 'count';
        }

        $chart = strtolower((string) ($raw['chart'] ?? 'bar'));
        if (! in_array($chart, ['bar', 'pie', 'line', 'none'], true)) {
            $chart = 'bar';
        }
        $dateGrouping = strtolower((string) ($raw['date_grouping'] ?? 'exact'));
        if (! in_array($dateGrouping, ['exact', 'day', 'week', 'month', 'year'], true)) {
            $dateGrouping = 'exact';
        }
        $sortBy = strtolower((string) ($raw['sort_by'] ?? 'metric'));
        if (! in_array($sortBy, ['metric', 'group'], true)) {
            $sortBy = 'metric';
        }
        $direction = strtolower((string) ($raw['direction'] ?? 'desc')) === 'asc' ? 'asc' : 'desc';
        $rowLimit = max(1, min(2000, (int) ($raw['row_limit'] ?? 500)));

        $filters = [];
        if (is_array($raw['filters'] ?? null)) {
            foreach ($raw['filters'] as $f) {
                if (! is_array($f)) {
                    continue;
                }
                $field = $pickField($f['field'] ?? null);
                $value = trim((string) ($f['value'] ?? ''));
                if ($field === null || $value === '') {
                    continue;
                }
                $filters[] = [
                    'field' => $field,
                    'op' => 'eq',
                    'value' => $value,
                ];
            }
        }

        $title = trim((string) ($raw['title'] ?? ''));
        if ($title === '') {
            $title = Str::limit($fallbackTitle, 120, '');
        }

        $groupBy = $pickField($raw['group_by'] ?? null);
        $groupBy2 = $pickField($raw['group_by_2'] ?? null);
        $matrixColumn = $pickField($raw['matrix_column'] ?? $raw['group_by_2'] ?? null);

        return [
            'title' => $title,
            'caption' => trim((string) ($raw['caption'] ?? '')) ?: null,
            'entity_slug' => $entitySlug,
            'format' => $format,
            'metric' => $metric,
            'metric_field' => $metricField ?? '',
            'group_by' => $groupBy ?? '',
            'group_by_2' => $groupBy2 ?? '',
            'matrix_column' => $matrixColumn ?? '',
            'date_grouping' => $dateGrouping,
            'chart' => $chart,
            'sort_by' => $sortBy,
            'direction' => $direction,
            'row_limit' => $rowLimit,
            'currency_prefix' => trim((string) ($raw['currency_prefix'] ?? '')),
            'filters' => $filters,
        ];
    }

    /**
     * @return array<string, mixed>|null
     */
    private function extractJsonObject(string $answer): ?array
    {
        $text = trim($answer);
        if ($text === '') {
            return null;
        }
        if (preg_match('/```(?:json)?\s*(\{.*?\})\s*```/is', $text, $m) === 1) {
            $text = $m[1];
        } else {
            $start = strpos($text, '{');
            $end = strrpos($text, '}');
            if ($start === false || $end === false || $end <= $start) {
                return null;
            }
            $text = substr($text, $start, $end - $start + 1);
        }

        $decoded = json_decode($text, true);

        return is_array($decoded) ? $decoded : null;
    }

    /**
     * @return list<array{slug: string, name: string, fields: list<array{name: string, label: string, type: string}>}>
     */
    private function entityCatalog(): array
    {
        $entities = DynEntity::query()
            ->where('is_active', true)
            ->with(['fields' => static function ($q): void {
                $q->orderBy('field_order');
            }])
            ->orderBy('sort_order')
            ->orderBy('name')
            ->limit(80)
            ->get();

        $out = [];
        foreach ($entities as $entity) {
            $fields = [];
            foreach ($entity->fields as $field) {
                if ($field->is_system_field || in_array($field->name, ['actions', 'workflows', 'print', 'id'], true)) {
                    continue;
                }
                $fields[] = [
                    'name' => (string) $field->name,
                    'label' => (string) ($field->label ?: $field->name),
                    'type' => (string) $field->type,
                ];
                if (count($fields) >= 40) {
                    break;
                }
            }
            $out[] = [
                'slug' => (string) $entity->slug,
                'name' => (string) $entity->name,
                'fields' => $fields,
            ];
        }

        return $out;
    }
}
