<?php

declare(strict_types=1);

use App\Modules\AdminOne\Http\Controllers\V1\AdminSettingsShowController;
use App\Modules\AdminOne\Http\Controllers\V1\AdminSettingsUpdateController;
use App\Modules\AdminOne\Http\Controllers\V1\RoleIndexController;
use App\Modules\AdminOne\Http\Controllers\V1\RoleStoreController;
use App\Modules\AdminOne\Http\Controllers\V1\RoleUpdateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantBillingShowController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserDeactivateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserDestroyController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserExportController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserImportController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserIndexController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserReactivateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserStoreController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserUpdateController;
use App\Modules\AssetOne\Http\Controllers\V1\AssetIndexController;
use App\Modules\AssetOne\Http\Controllers\V1\AssetOneDashboardController;
use App\Modules\FiberOne\Http\Controllers\V1\FiberOneDashboardController;
use App\Modules\FiberOne\Http\Controllers\V1\FiberRouteIndexController;
use App\Modules\Identity\Http\Controllers\V1\TenantHealthController;
use App\Modules\Identity\Http\Controllers\V1\TenantAuthController;
use App\Modules\Identity\Http\Controllers\V1\TenantSsoConfigController;
use App\Modules\Identity\Http\Controllers\V1\TenantSsoController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectApprovalIndexController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectApprovalStoreController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectApprovalUpdateController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectMilestoneUpdateController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectIndexController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectShowController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectStoreController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectUpdateController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectOneDashboardController;
use App\Modules\Rollout\Http\Controllers\V1\CmeDailyReportStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutAssignableUsersController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBatchStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBulkPhaseDatesController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBulkPhaseDatesGridController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBulkUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDecideController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDelegationDestroyController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDelegationIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDelegationStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalExportController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalSubmitController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutDeliveryPeriodStartController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutMapController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutFileShowController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutFileStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutPlaybookConfigureController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutPlaybookStatusController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramCancelController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramExportController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutActivityIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramShowController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutRfiRecordedController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutTimelinePhaseGateUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutTssrApprovedController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateRejectController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateSelectController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateStoreController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\SiteHuntingLogStoreController;
use App\Modules\Rollout\Http\Controllers\V1\SiteProfitabilityShowController;
use App\Modules\Rollout\Http\Controllers\V1\SiteProfitabilityUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayDestroyController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayIndexController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidaySeedPhilippinesController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayStoreController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayUpdateController;
use App\Modules\Sites\Http\Controllers\V1\SiteIndexController;
use App\Modules\TowerOne\Http\Controllers\V1\TowerIndexController;
use App\Modules\TowerOne\Http\Controllers\V1\TowerOneDashboardController;
use Illuminate\Support\Facades\Route;

Route::get('health', TenantHealthController::class)->name('api.tenant.v1.health');

Route::prefix('auth')->group(function () {
    Route::post('login', [TenantAuthController::class, 'login'])->name('api.tenant.v1.auth.login');
    Route::post('refresh', [TenantAuthController::class, 'refresh'])->name('api.tenant.v1.auth.refresh');
    Route::post('mfa/challenge', [TenantAuthController::class, 'mfaChallenge'])->name('api.tenant.v1.auth.mfa.challenge');
    Route::post('mfa/verify', [TenantAuthController::class, 'mfaVerify'])->name('api.tenant.v1.auth.mfa.verify');
    Route::post('mfa/recovery', [TenantAuthController::class, 'mfaRecovery'])->name('api.tenant.v1.auth.mfa.recovery');
    Route::get('sso/azure/redirect', [TenantSsoController::class, 'redirect'])->name('api.tenant.v1.auth.sso.azure.redirect');
    Route::get('sso/azure/callback', [TenantSsoController::class, 'callback'])->name('api.tenant.v1.auth.sso.azure.callback');
});

Route::middleware(['tenant.sanctum', 'auth:sanctum', 'auth.session', 'auth.mfa'])->group(function () {
    Route::get('me', [TenantAuthController::class, 'me'])->name('api.tenant.v1.auth.me');
    Route::post('auth/logout', [TenantAuthController::class, 'logout'])->name('api.tenant.v1.auth.logout');
    Route::post('auth/logout-all', [TenantAuthController::class, 'logoutAll'])->name('api.tenant.v1.auth.logout_all');
    Route::get('auth/sessions', [TenantAuthController::class, 'sessions'])->name('api.tenant.v1.auth.sessions');
    Route::delete('auth/sessions/{sessionId}', [TenantAuthController::class, 'revokeSession'])->name('api.tenant.v1.auth.sessions.revoke');
    Route::get('sites', SiteIndexController::class)->name('api.tenant.v1.sites.index');
    Route::get('project-one/dashboard', ProjectOneDashboardController::class)->name('api.tenant.v1.project_one.dashboard');
    Route::get('project-one/assignable-users', RolloutAssignableUsersController::class)->name('api.tenant.v1.project_one.assignable_users.index');
    Route::get('project-one/rollouts/export', RolloutProgramExportController::class)->name('api.tenant.v1.project_one.rollouts.export');
    Route::get('project-one/rollouts', RolloutProgramIndexController::class)->name('api.tenant.v1.project_one.rollouts.index');
    Route::post('project-one/rollouts', RolloutProgramStoreController::class)->name('api.tenant.v1.project_one.rollouts.store');
    Route::post('project-one/rollouts/bulk-update', RolloutBulkUpdateController::class)->name('api.tenant.v1.project_one.rollouts.bulk_update');
    Route::post('project-one/rollouts/bulk-phase-dates', RolloutBulkPhaseDatesController::class)->name('api.tenant.v1.project_one.rollouts.bulk_phase_dates');
    Route::post('project-one/rollouts/bulk-phase-dates-grid', RolloutBulkPhaseDatesGridController::class)->name('api.tenant.v1.project_one.rollouts.bulk_phase_dates_grid');
    Route::post('project-one/rollout-batches', RolloutBatchStoreController::class)->name('api.tenant.v1.project_one.rollout_batches.store');
    Route::get('project-one/rollouts/{rollout}', RolloutProgramShowController::class)->name('api.tenant.v1.project_one.rollouts.show');
    Route::get('project-one/rollouts/{rollout}/activity', RolloutActivityIndexController::class)->name('api.tenant.v1.project_one.rollouts.activity');
    Route::get('project-one/rollouts/{rollout}/map', RolloutMapController::class)->name('api.tenant.v1.project_one.rollouts.map');
    Route::patch('project-one/rollouts/{rollout}', RolloutProgramUpdateController::class)->name('api.tenant.v1.project_one.rollouts.update');
    Route::post('project-one/rollouts/{rollout}/cancel', RolloutProgramCancelController::class)->name('api.tenant.v1.project_one.rollouts.cancel');
    Route::post('project-one/files', RolloutFileStoreController::class)->name('api.tenant.v1.project_one.files.store');
    Route::get('project-one/files/{file}', RolloutFileShowController::class)->name('api.tenant.v1.project_one.files.show');
    Route::post('project-one/rollouts/{rollout}/tssr-approved', RolloutTssrApprovedController::class)->name('api.tenant.v1.project_one.rollouts.tssr_approved');
    Route::post('project-one/rollouts/{rollout}/delivery-period-start', RolloutDeliveryPeriodStartController::class)->name('api.tenant.v1.project_one.rollouts.delivery_period_start');
    Route::post('project-one/rollouts/{rollout}/rfi-recorded', RolloutRfiRecordedController::class)->name('api.tenant.v1.project_one.rollouts.rfi_recorded');
    Route::patch('project-one/rollout-phases/{phase}/gate', RolloutTimelinePhaseGateUpdateController::class)->name('api.tenant.v1.project_one.rollout_phases.gate');
    Route::get('project-one/gate-approvals', RolloutGateApprovalIndexController::class)->name('api.tenant.v1.project_one.gate_approvals.index');
    Route::get('project-one/gate-approvals/export', RolloutGateApprovalExportController::class)->name('api.tenant.v1.project_one.gate_approvals.export');
    Route::get('project-one/gate-approval-delegations', RolloutGateApprovalDelegationIndexController::class)->name('api.tenant.v1.project_one.gate_approval_delegations.index');
    Route::post('project-one/gate-approval-delegations', RolloutGateApprovalDelegationStoreController::class)->name('api.tenant.v1.project_one.gate_approval_delegations.store');
    Route::delete('project-one/gate-approval-delegations/{delegation}', RolloutGateApprovalDelegationDestroyController::class)->name('api.tenant.v1.project_one.gate_approval_delegations.destroy');
    Route::post('project-one/rollout-phases/{phase}/gate-approvals', RolloutGateApprovalSubmitController::class)->name('api.tenant.v1.project_one.rollout_phases.gate_approvals.submit');
    Route::post('project-one/gate-approvals/{gateApproval}/decide', RolloutGateApprovalDecideController::class)->name('api.tenant.v1.project_one.gate_approvals.decide');
    Route::post('project-one/rollouts/{rollout}/candidates', SiteCandidateStoreController::class)->name('api.tenant.v1.project_one.rollouts.candidates.store');
    Route::patch('project-one/candidates/{candidate}', SiteCandidateUpdateController::class)->name('api.tenant.v1.project_one.candidates.update');
    Route::post('project-one/candidates/{candidate}/reject', SiteCandidateRejectController::class)->name('api.tenant.v1.project_one.candidates.reject');
    Route::post('project-one/candidates/{candidate}/select', SiteCandidateSelectController::class)->name('api.tenant.v1.project_one.candidates.select');
    Route::post('project-one/rollouts/{rollout}/hunting-logs', SiteHuntingLogStoreController::class)->name('api.tenant.v1.project_one.rollouts.hunting_logs.store');
    Route::post('project-one/rollouts/{rollout}/cme-reports', CmeDailyReportStoreController::class)->name('api.tenant.v1.project_one.rollouts.cme_reports.store');
    Route::get('project-one/rollouts/{rollout}/profitability', SiteProfitabilityShowController::class)->name('api.tenant.v1.project_one.rollouts.profitability.show');
    Route::patch('project-one/rollouts/{rollout}/profitability', SiteProfitabilityUpdateController::class)->name('api.tenant.v1.project_one.rollouts.profitability.update');
    Route::get('project-one/rollout-playbook', RolloutPlaybookStatusController::class)->name('api.tenant.v1.project_one.rollout_playbook.status');
    Route::patch('project-one/rollout-playbook', RolloutPlaybookConfigureController::class)->name('api.tenant.v1.project_one.rollout_playbook.configure');
    Route::get('project-one/public-holidays', TenantPublicHolidayIndexController::class)->name('api.tenant.v1.project_one.public_holidays.index');
    Route::post('project-one/public-holidays/seed-philippines', TenantPublicHolidaySeedPhilippinesController::class)->name('api.tenant.v1.project_one.public_holidays.seed_philippines');
    Route::post('project-one/public-holidays', TenantPublicHolidayStoreController::class)->name('api.tenant.v1.project_one.public_holidays.store');
    Route::patch('project-one/public-holidays/{holiday}', TenantPublicHolidayUpdateController::class)->name('api.tenant.v1.project_one.public_holidays.update');
    Route::delete('project-one/public-holidays/{holiday}', TenantPublicHolidayDestroyController::class)->name('api.tenant.v1.project_one.public_holidays.destroy');
    Route::get('project-one/projects', ProjectIndexController::class)->name('api.tenant.v1.project_one.projects.index');
    Route::post('project-one/projects', ProjectStoreController::class)->name('api.tenant.v1.project_one.projects.store');
    Route::get('project-one/projects/{project}', ProjectShowController::class)->name('api.tenant.v1.project_one.projects.show');
    Route::patch('project-one/projects/{project}', ProjectUpdateController::class)->name('api.tenant.v1.project_one.projects.update');
    Route::get('project-one/approvals', ProjectApprovalIndexController::class)->name('api.tenant.v1.project_one.approvals.index');
    Route::post('project-one/approvals', ProjectApprovalStoreController::class)->name('api.tenant.v1.project_one.approvals.store');
    Route::patch('project-one/approvals/{approval}', ProjectApprovalUpdateController::class)->name('api.tenant.v1.project_one.approvals.update');
    Route::patch('project-one/milestones/{milestone}', ProjectMilestoneUpdateController::class)->name('api.tenant.v1.project_one.milestones.update');
    Route::get('tower-one/dashboard', TowerOneDashboardController::class)->name('api.tenant.v1.tower_one.dashboard');
    Route::get('tower-one/towers', TowerIndexController::class)->name('api.tenant.v1.tower_one.towers.index');
    Route::get('fiber-one/dashboard', FiberOneDashboardController::class)->name('api.tenant.v1.fiber_one.dashboard');
    Route::get('fiber-one/routes', FiberRouteIndexController::class)->name('api.tenant.v1.fiber_one.routes.index');
    Route::get('asset-one/dashboard', AssetOneDashboardController::class)->name('api.tenant.v1.asset_one.dashboard');
    Route::get('asset-one/assets', AssetIndexController::class)->name('api.tenant.v1.asset_one.assets.index');
    Route::get('admin/sso/config', [TenantSsoConfigController::class, 'show'])->name('api.tenant.v1.admin.sso.config.show');
    Route::put('admin/sso/config', [TenantSsoConfigController::class, 'update'])->name('api.tenant.v1.admin.sso.config.update');
    Route::post('admin/sso/test-connection', [TenantSsoConfigController::class, 'testConnection'])->name('api.tenant.v1.admin.sso.test');
    Route::post('auth/mfa/recovery-codes/regenerate', [TenantAuthController::class, 'mfaRecoveryCodesRegenerate'])->name('api.tenant.v1.auth.mfa.recovery_codes.regenerate');

    Route::prefix('admin')->group(function () {
        Route::get('users', TenantUserIndexController::class)->name('api.tenant.v1.admin.users.index');
        Route::get('users/export', TenantUserExportController::class)->name('api.tenant.v1.admin.users.export');
        Route::post('users', TenantUserStoreController::class)->name('api.tenant.v1.admin.users.store');
        Route::post('users/import', TenantUserImportController::class)->name('api.tenant.v1.admin.users.import');
        Route::patch('users/{user}', TenantUserUpdateController::class)->name('api.tenant.v1.admin.users.update');
        Route::post('users/{user}/deactivate', TenantUserDeactivateController::class)->name('api.tenant.v1.admin.users.deactivate');
        Route::post('users/{user}/reactivate', TenantUserReactivateController::class)->name('api.tenant.v1.admin.users.reactivate');
        Route::delete('users/{user}', TenantUserDestroyController::class)->name('api.tenant.v1.admin.users.destroy');
        Route::get('roles', RoleIndexController::class)->name('api.tenant.v1.admin.roles.index');
        Route::post('roles', RoleStoreController::class)->name('api.tenant.v1.admin.roles.store');
        Route::patch('roles/{role}', RoleUpdateController::class)->name('api.tenant.v1.admin.roles.update');
        Route::get('billing', TenantBillingShowController::class)->name('api.tenant.v1.admin.billing.show');
        Route::get('settings', AdminSettingsShowController::class)->name('api.tenant.v1.admin.settings.show');
        Route::patch('settings', AdminSettingsUpdateController::class)->name('api.tenant.v1.admin.settings.update');
    });
});

Route::middleware(['tenant.sanctum', 'auth:sanctum', 'auth.session'])->group(function () {
    Route::post('auth/mfa/enroll/start', [TenantAuthController::class, 'mfaEnrollStart'])->name('api.tenant.v1.auth.mfa.enroll.start');
    Route::post('auth/mfa/enroll/complete', [TenantAuthController::class, 'mfaEnrollComplete'])->name('api.tenant.v1.auth.mfa.enroll.complete');
});
