<?php

declare(strict_types=1);

use App\Modules\AdminOne\Http\Controllers\V1\AdminSettingsShowController;
use App\Modules\AdminOne\Http\Controllers\V1\AdminSettingsUpdateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantWorkspaceDashboardController;
use App\Modules\Workspace\Http\Controllers\V1\WorkspaceSearchController;
use App\Modules\AdminOne\Http\Controllers\V1\RoleIndexController;
use App\Modules\AdminOne\Http\Controllers\V1\RoleStoreController;
use App\Modules\AdminOne\Http\Controllers\V1\RoleUpdateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantBillingCheckoutSessionStoreController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantBillingUsageShowController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantBillingPortalSessionStoreController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantBillingShowController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserImpersonateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserDeactivateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserDestroyController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserExportController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserImportController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserIndexController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserReactivateController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserStoreController;
use App\Modules\AdminOne\Http\Controllers\V1\TenantUserUpdateController;
use App\Modules\AssetOne\Http\Controllers\V1\AssetIndexController;
use App\Modules\AssetOne\Http\Controllers\V1\AssetShowController;
use App\Modules\AssetOne\Http\Controllers\V1\AssetOneDashboardController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingAssignableUsersController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingAttachmentDownloadController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingAttachmentStoreController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingCommentStoreController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingDashboardController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingMetadataController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingTicketIndexController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingTicketShowController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingTicketStoreController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingSettingsShowController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingSettingsTestEmailController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingSettingsTestWebhookController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingSettingsUpdateController;
use App\Modules\Ticketing\Http\Controllers\V1\TicketingTicketUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalApprovalDecideController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalApprovalIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalApprovalRerouteController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalAssignableUsersController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormLogoStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalAuditIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalAttachmentDownloadController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalDashboardController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormExportController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormImportController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormPublishController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormRevisionsIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormRevisionRestoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalAdminStatsController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormTemplateCustomDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormTemplateCustomShowController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormTemplateCustomStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormTemplateCustomUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormTemplateFinanceBundleStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormTemplateStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormTemplatesIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormMyDraftController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormShowController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalFormValidateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalHealthController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalManagerLookupTestController;
use App\Modules\Notifications\Http\Controllers\V1\TenantNotificationIndexController;
use App\Modules\Notifications\Http\Controllers\V1\TenantNotificationMarkAllReadController;
use App\Modules\Notifications\Http\Controllers\V1\TenantNotificationMarkReadController;
use App\Modules\Notifications\Http\Controllers\V1\TenantNotificationUnreadCountController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalNotificationIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalNotificationMarkAllReadController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalNotificationMarkReadController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalNotificationUnreadCountController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPublicFormLinkIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPublicFormLinkRevokeController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPublicFormLinkRotateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPublicFormLinkStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPublicFormShowController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPublicSubmissionAttachmentStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPublicSubmissionStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPdfLayoutDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPdfLayoutShowController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPdfLayoutUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionAttachmentStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionExportController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionPrintDataController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionCancelController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionCommentIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionCommentStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionResubmitController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionShowController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionDraftUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionSubmitDraftController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalCashAdvanceOpenController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalPurchaseRequisitionOpenController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalDelegationDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalDelegationIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalDelegationStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalDocumentLinkDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalDocumentLinkStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataLookupController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataRowBulkStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataRowDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataRowIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataRowStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataRowUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataSetDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataSetIndexController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataSetStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMasterDataSetUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMeAttachmentDestroyController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMeAttachmentStoreController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMeProfileController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMeSignatureUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalMetadataController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSettingsPublicController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSettingsShowController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSettingsTestEmailController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSettingsUpdateController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionDcfResubmitController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionManualFollowUpController;
use App\Modules\EApproval\Http\Controllers\V1\EApprovalSubmissionRevisionController;
use App\Modules\FiberOne\Http\Controllers\V1\FiberOneDashboardController;
use App\Modules\FiberOne\Http\Controllers\V1\FiberRouteIndexController;
use App\Modules\Identity\Http\Controllers\V1\TenantHealthController;
use App\Modules\Identity\Http\Controllers\V1\TenantAuthController;
use App\Modules\Identity\Http\Controllers\V1\TenantImpersonationStopController;
use App\Modules\Identity\Http\Controllers\V1\TenantSsoAzureStatusController;
use App\Modules\Identity\Http\Controllers\V1\TenantSsoConfigController;
use App\Modules\Identity\Http\Controllers\V1\TenantSsoController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectApprovalIndexController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectApprovalStoreController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectApprovalUpdateController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectMilestoneUpdateController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectIndexController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectShowController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectStoreController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectUpdateController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectOneDashboardController;
use App\Modules\ProjectOne\Http\Controllers\V1\ProjectOneDashboardMapController;
use App\Modules\Rollout\Http\Controllers\V1\CmeDailyReportStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutAssignableUsersController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBatchStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBulkPhaseDatesController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBulkPhaseDatesGridController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutBulkUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDecideController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDelegationDestroyController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDelegationIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalDelegationStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalExportController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutGateApprovalSubmitController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutDeliveryPeriodStartController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutMapController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutFileShowController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutFileStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutPlaybookConfigureController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutPlaybookStatusController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramCancelController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramExportController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutActivityIndexController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramShowController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramStoreController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutProgramUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutRfiRecordedController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutTimelinePhaseGateUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\RolloutTssrApprovedController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateRejectController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateSelectController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateStoreController;
use App\Modules\Rollout\Http\Controllers\V1\SiteCandidateUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\SiteHuntingLogStoreController;
use App\Modules\Rollout\Http\Controllers\V1\SiteProfitabilityShowController;
use App\Modules\Rollout\Http\Controllers\V1\SiteProfitabilityUpdateController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayDestroyController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayIndexController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidaySeedPhilippinesController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayStoreController;
use App\Modules\Rollout\Http\Controllers\V1\TenantPublicHolidayUpdateController;
use App\Modules\Sites\Http\Controllers\V1\SiteIndexController;
use App\Modules\Sites\Http\Controllers\V1\SiteShowController;
use App\Modules\TowerOne\Http\Controllers\V1\TowerIndexController;
use App\Modules\TowerOne\Http\Controllers\V1\TowerShowController;
use App\Modules\TowerOne\Http\Controllers\V1\TowerOneDashboardController;
use Illuminate\Support\Facades\Route;

Route::get('health', TenantHealthController::class)->name('api.tenant.v1.health');

Route::prefix('auth')->group(function () {
    Route::post('login', [TenantAuthController::class, 'login'])->name('api.tenant.v1.auth.login');
    Route::post('refresh', [TenantAuthController::class, 'refresh'])->name('api.tenant.v1.auth.refresh');
    Route::post('mfa/challenge', [TenantAuthController::class, 'mfaChallenge'])->name('api.tenant.v1.auth.mfa.challenge');
    Route::post('mfa/verify', [TenantAuthController::class, 'mfaVerify'])->name('api.tenant.v1.auth.mfa.verify');
    Route::post('mfa/recovery', [TenantAuthController::class, 'mfaRecovery'])->name('api.tenant.v1.auth.mfa.recovery');
    Route::get('sso/azure/status', TenantSsoAzureStatusController::class)->name('api.tenant.v1.auth.sso.azure.status');
    Route::get('sso/azure/redirect', [TenantSsoController::class, 'redirect'])->name('api.tenant.v1.auth.sso.azure.redirect');
    Route::get('sso/azure/callback', [TenantSsoController::class, 'callback'])->name('api.tenant.v1.auth.sso.azure.callback');
});

Route::middleware(['throttle:e-approval-public'])->prefix('public/e-approval')->group(function () {
    Route::get('forms/{token}', EApprovalPublicFormShowController::class)->name('api.tenant.v1.e_approval.public.forms.show');
    Route::post('forms/{token}/submissions', EApprovalPublicSubmissionStoreController::class)->name('api.tenant.v1.e_approval.public.submissions.store');
    Route::post('forms/{token}/submissions/{submission}/attachments', EApprovalPublicSubmissionAttachmentStoreController::class)
        ->name('api.tenant.v1.e_approval.public.submissions.attachments.store');
});

Route::middleware(['tenant.sanctum', 'auth:sanctum', 'auth.session', 'auth.mfa'])->group(function () {
    Route::get('me', [TenantAuthController::class, 'me'])->name('api.tenant.v1.auth.me');
    Route::post('auth/logout', [TenantAuthController::class, 'logout'])->name('api.tenant.v1.auth.logout');
    Route::post('auth/logout-all', [TenantAuthController::class, 'logoutAll'])->name('api.tenant.v1.auth.logout_all');
    Route::get('auth/sessions', [TenantAuthController::class, 'sessions'])->name('api.tenant.v1.auth.sessions');
    Route::delete('auth/sessions/{sessionId}', [TenantAuthController::class, 'revokeSession'])->name('api.tenant.v1.auth.sessions.revoke');
    Route::post('auth/impersonation/stop', TenantImpersonationStopController::class)->name('api.tenant.v1.auth.impersonation.stop');
    Route::get('sites', SiteIndexController::class)->name('api.tenant.v1.sites.index');
    Route::get('sites/{site}', SiteShowController::class)->name('api.tenant.v1.sites.show');
    Route::get('notifications', TenantNotificationIndexController::class)->name('api.tenant.v1.notifications.index');
    Route::get('notifications/unread-count', TenantNotificationUnreadCountController::class)->name('api.tenant.v1.notifications.unread_count');
    Route::post('notifications/mark-all-read', TenantNotificationMarkAllReadController::class)->name('api.tenant.v1.notifications.mark_all_read');
    Route::post('notifications/{notification}/read', TenantNotificationMarkReadController::class)->name('api.tenant.v1.notifications.read');
    Route::get('dashboard', TenantWorkspaceDashboardController::class)->name('api.tenant.v1.dashboard');
    Route::get('workspace/search', WorkspaceSearchController::class)->name('api.tenant.v1.workspace.search');
    Route::get('project-one/dashboard', ProjectOneDashboardController::class)->name('api.tenant.v1.project_one.dashboard');
    Route::get('project-one/dashboard/map', ProjectOneDashboardMapController::class)->name('api.tenant.v1.project_one.dashboard.map');
    Route::get('project-one/assignable-users', RolloutAssignableUsersController::class)->name('api.tenant.v1.project_one.assignable_users.index');
    Route::get('project-one/rollouts/export', RolloutProgramExportController::class)->name('api.tenant.v1.project_one.rollouts.export');
    Route::get('project-one/rollouts', RolloutProgramIndexController::class)->name('api.tenant.v1.project_one.rollouts.index');
    Route::post('project-one/rollouts', RolloutProgramStoreController::class)->name('api.tenant.v1.project_one.rollouts.store');
    Route::post('project-one/rollouts/bulk-update', RolloutBulkUpdateController::class)->name('api.tenant.v1.project_one.rollouts.bulk_update');
    Route::post('project-one/rollouts/bulk-phase-dates', RolloutBulkPhaseDatesController::class)->name('api.tenant.v1.project_one.rollouts.bulk_phase_dates');
    Route::post('project-one/rollouts/bulk-phase-dates-grid', RolloutBulkPhaseDatesGridController::class)->name('api.tenant.v1.project_one.rollouts.bulk_phase_dates_grid');
    Route::post('project-one/rollout-batches', RolloutBatchStoreController::class)->name('api.tenant.v1.project_one.rollout_batches.store');
    Route::get('project-one/rollouts/{rollout}', RolloutProgramShowController::class)->name('api.tenant.v1.project_one.rollouts.show');
    Route::get('project-one/rollouts/{rollout}/activity', RolloutActivityIndexController::class)->name('api.tenant.v1.project_one.rollouts.activity');
    Route::get('project-one/rollouts/{rollout}/map', RolloutMapController::class)->name('api.tenant.v1.project_one.rollouts.map');
    Route::patch('project-one/rollouts/{rollout}', RolloutProgramUpdateController::class)->name('api.tenant.v1.project_one.rollouts.update');
    Route::post('project-one/rollouts/{rollout}/cancel', RolloutProgramCancelController::class)->name('api.tenant.v1.project_one.rollouts.cancel');
    Route::post('project-one/files', RolloutFileStoreController::class)->name('api.tenant.v1.project_one.files.store');
    Route::get('project-one/files/{file}', RolloutFileShowController::class)->name('api.tenant.v1.project_one.files.show');
    Route::post('project-one/rollouts/{rollout}/tssr-approved', RolloutTssrApprovedController::class)->name('api.tenant.v1.project_one.rollouts.tssr_approved');
    Route::post('project-one/rollouts/{rollout}/delivery-period-start', RolloutDeliveryPeriodStartController::class)->name('api.tenant.v1.project_one.rollouts.delivery_period_start');
    Route::post('project-one/rollouts/{rollout}/rfi-recorded', RolloutRfiRecordedController::class)->name('api.tenant.v1.project_one.rollouts.rfi_recorded');
    Route::patch('project-one/rollout-phases/{phase}/gate', RolloutTimelinePhaseGateUpdateController::class)->name('api.tenant.v1.project_one.rollout_phases.gate');
    Route::get('project-one/gate-approvals', RolloutGateApprovalIndexController::class)->name('api.tenant.v1.project_one.gate_approvals.index');
    Route::get('project-one/gate-approvals/export', RolloutGateApprovalExportController::class)->name('api.tenant.v1.project_one.gate_approvals.export');
    Route::get('project-one/gate-approval-delegations', RolloutGateApprovalDelegationIndexController::class)->name('api.tenant.v1.project_one.gate_approval_delegations.index');
    Route::post('project-one/gate-approval-delegations', RolloutGateApprovalDelegationStoreController::class)->name('api.tenant.v1.project_one.gate_approval_delegations.store');
    Route::delete('project-one/gate-approval-delegations/{delegation}', RolloutGateApprovalDelegationDestroyController::class)->name('api.tenant.v1.project_one.gate_approval_delegations.destroy');
    Route::post('project-one/rollout-phases/{phase}/gate-approvals', RolloutGateApprovalSubmitController::class)->name('api.tenant.v1.project_one.rollout_phases.gate_approvals.submit');
    Route::post('project-one/gate-approvals/{gateApproval}/decide', RolloutGateApprovalDecideController::class)->name('api.tenant.v1.project_one.gate_approvals.decide');
    Route::post('project-one/rollouts/{rollout}/candidates', SiteCandidateStoreController::class)->name('api.tenant.v1.project_one.rollouts.candidates.store');
    Route::patch('project-one/candidates/{candidate}', SiteCandidateUpdateController::class)->name('api.tenant.v1.project_one.candidates.update');
    Route::post('project-one/candidates/{candidate}/reject', SiteCandidateRejectController::class)->name('api.tenant.v1.project_one.candidates.reject');
    Route::post('project-one/candidates/{candidate}/select', SiteCandidateSelectController::class)->name('api.tenant.v1.project_one.candidates.select');
    Route::post('project-one/rollouts/{rollout}/hunting-logs', SiteHuntingLogStoreController::class)->name('api.tenant.v1.project_one.rollouts.hunting_logs.store');
    Route::post('project-one/rollouts/{rollout}/cme-reports', CmeDailyReportStoreController::class)->name('api.tenant.v1.project_one.rollouts.cme_reports.store');
    Route::get('project-one/rollouts/{rollout}/profitability', SiteProfitabilityShowController::class)->name('api.tenant.v1.project_one.rollouts.profitability.show');
    Route::patch('project-one/rollouts/{rollout}/profitability', SiteProfitabilityUpdateController::class)->name('api.tenant.v1.project_one.rollouts.profitability.update');
    Route::get('project-one/rollout-playbook', RolloutPlaybookStatusController::class)->name('api.tenant.v1.project_one.rollout_playbook.status');
    Route::patch('project-one/rollout-playbook', RolloutPlaybookConfigureController::class)->name('api.tenant.v1.project_one.rollout_playbook.configure');
    Route::get('project-one/public-holidays', TenantPublicHolidayIndexController::class)->name('api.tenant.v1.project_one.public_holidays.index');
    Route::post('project-one/public-holidays/seed-philippines', TenantPublicHolidaySeedPhilippinesController::class)->name('api.tenant.v1.project_one.public_holidays.seed_philippines');
    Route::post('project-one/public-holidays', TenantPublicHolidayStoreController::class)->name('api.tenant.v1.project_one.public_holidays.store');
    Route::patch('project-one/public-holidays/{holiday}', TenantPublicHolidayUpdateController::class)->name('api.tenant.v1.project_one.public_holidays.update');
    Route::delete('project-one/public-holidays/{holiday}', TenantPublicHolidayDestroyController::class)->name('api.tenant.v1.project_one.public_holidays.destroy');
    Route::get('project-one/projects', ProjectIndexController::class)->name('api.tenant.v1.project_one.projects.index');
    Route::post('project-one/projects', ProjectStoreController::class)->name('api.tenant.v1.project_one.projects.store');
    Route::get('project-one/projects/{project}', ProjectShowController::class)->name('api.tenant.v1.project_one.projects.show');
    Route::patch('project-one/projects/{project}', ProjectUpdateController::class)->name('api.tenant.v1.project_one.projects.update');
    Route::get('project-one/approvals', ProjectApprovalIndexController::class)->name('api.tenant.v1.project_one.approvals.index');
    Route::post('project-one/approvals', ProjectApprovalStoreController::class)->name('api.tenant.v1.project_one.approvals.store');
    Route::patch('project-one/approvals/{approval}', ProjectApprovalUpdateController::class)->name('api.tenant.v1.project_one.approvals.update');
    Route::patch('project-one/milestones/{milestone}', ProjectMilestoneUpdateController::class)->name('api.tenant.v1.project_one.milestones.update');
    Route::get('tower-one/dashboard', TowerOneDashboardController::class)->name('api.tenant.v1.tower_one.dashboard');
    Route::get('tower-one/towers', TowerIndexController::class)->name('api.tenant.v1.tower_one.towers.index');
    Route::get('tower-one/towers/{tower}', TowerShowController::class)->name('api.tenant.v1.tower_one.towers.show');
    Route::get('fiber-one/dashboard', FiberOneDashboardController::class)->name('api.tenant.v1.fiber_one.dashboard');
    Route::get('fiber-one/routes', FiberRouteIndexController::class)->name('api.tenant.v1.fiber_one.routes.index');
    Route::get('asset-one/dashboard', AssetOneDashboardController::class)->name('api.tenant.v1.asset_one.dashboard');
    Route::get('asset-one/assets', AssetIndexController::class)->name('api.tenant.v1.asset_one.assets.index');
    Route::get('asset-one/assets/{asset}', AssetShowController::class)->name('api.tenant.v1.asset_one.assets.show');
    Route::get('ticketing/dashboard', TicketingDashboardController::class)->name('api.tenant.v1.ticketing.dashboard');
    Route::get('ticketing/settings', TicketingSettingsShowController::class)->name('api.tenant.v1.ticketing.settings.show');
    Route::put('ticketing/settings', TicketingSettingsUpdateController::class)->name('api.tenant.v1.ticketing.settings.update');
    Route::post('ticketing/settings/test-email', TicketingSettingsTestEmailController::class)->name('api.tenant.v1.ticketing.settings.test_email');
    Route::post('ticketing/settings/test-webhook', TicketingSettingsTestWebhookController::class)->name('api.tenant.v1.ticketing.settings.test_webhook');
    Route::get('ticketing/metadata', TicketingMetadataController::class)->name('api.tenant.v1.ticketing.metadata');
    Route::get('ticketing/assignable-users', TicketingAssignableUsersController::class)->name('api.tenant.v1.ticketing.assignable_users');
    Route::get('ticketing/tickets', TicketingTicketIndexController::class)->name('api.tenant.v1.ticketing.tickets.index');
    Route::post('ticketing/tickets', TicketingTicketStoreController::class)->name('api.tenant.v1.ticketing.tickets.store');
    Route::get('ticketing/tickets/{ticket}', TicketingTicketShowController::class)->name('api.tenant.v1.ticketing.tickets.show');
    Route::patch('ticketing/tickets/{ticket}', TicketingTicketUpdateController::class)->name('api.tenant.v1.ticketing.tickets.update');
    Route::post('ticketing/tickets/{ticket}/comments', TicketingCommentStoreController::class)->name('api.tenant.v1.ticketing.tickets.comments.store');
    Route::post('ticketing/tickets/{ticket}/attachments', TicketingAttachmentStoreController::class)->name('api.tenant.v1.ticketing.tickets.attachments.store');
    Route::get('ticketing/attachments/{attachment}', TicketingAttachmentDownloadController::class)->name('api.tenant.v1.ticketing.attachments.show');
    Route::get('e-approval/health', EApprovalHealthController::class)->name('api.tenant.v1.e_approval.health');
    Route::get('e-approval/assignable-users', EApprovalAssignableUsersController::class)->name('api.tenant.v1.e_approval.assignable_users');
    Route::post('e-approval/workflow/test-manager-lookup', EApprovalManagerLookupTestController::class)->name('api.tenant.v1.e_approval.workflow.test_manager_lookup');
    Route::get('e-approval/dashboard', EApprovalDashboardController::class)->name('api.tenant.v1.e_approval.dashboard');
    Route::get('e-approval/admin/stats', EApprovalAdminStatsController::class)->name('api.tenant.v1.e_approval.admin.stats');
    Route::get('e-approval/form-templates', EApprovalFormTemplatesIndexController::class)->name('api.tenant.v1.e_approval.form_templates.index');
    Route::post('e-approval/form-templates', EApprovalFormTemplateStoreController::class)->name('api.tenant.v1.e_approval.form_templates.store');
    Route::post('e-approval/form-templates/finance-procurement-bundle', EApprovalFormTemplateFinanceBundleStoreController::class)->name('api.tenant.v1.e_approval.form_templates.finance_bundle.store');
    Route::post('e-approval/form-templates/custom', EApprovalFormTemplateCustomStoreController::class)->name('api.tenant.v1.e_approval.form_templates.custom.store');
    Route::get('e-approval/form-templates/custom/{templateId}', EApprovalFormTemplateCustomShowController::class)->name('api.tenant.v1.e_approval.form_templates.custom.show');
    Route::put('e-approval/form-templates/custom/{templateId}', EApprovalFormTemplateCustomUpdateController::class)->name('api.tenant.v1.e_approval.form_templates.custom.update');
    Route::delete('e-approval/form-templates/custom/{templateId}', EApprovalFormTemplateCustomDestroyController::class)->name('api.tenant.v1.e_approval.form_templates.custom.destroy');
    Route::get('e-approval/forms', EApprovalFormIndexController::class)->name('api.tenant.v1.e_approval.forms.index');
    Route::post('e-approval/forms', EApprovalFormStoreController::class)->name('api.tenant.v1.e_approval.forms.store');
    Route::post('e-approval/forms/import', EApprovalFormImportController::class)->name('api.tenant.v1.e_approval.forms.import');
    Route::post('e-approval/forms/validate', EApprovalFormValidateController::class)->name('api.tenant.v1.e_approval.forms.validate');
    Route::get('e-approval/audit', EApprovalAuditIndexController::class)->name('api.tenant.v1.e_approval.audit.index');
    Route::get('e-approval/submissions/export', EApprovalSubmissionExportController::class)->name('api.tenant.v1.e_approval.submissions.export');
    Route::get('e-approval/forms/{form}/revisions', EApprovalFormRevisionsIndexController::class)->name('api.tenant.v1.e_approval.forms.revisions');
    Route::post('e-approval/forms/{form}/revisions/{revision}/restore', EApprovalFormRevisionRestoreController::class)->name('api.tenant.v1.e_approval.forms.revisions.restore');
    Route::get('e-approval/forms/{form}/my-draft', EApprovalFormMyDraftController::class)->name('api.tenant.v1.e_approval.forms.my_draft');
    Route::get('e-approval/forms/{form}', EApprovalFormShowController::class)->name('api.tenant.v1.e_approval.forms.show');
    Route::put('e-approval/forms/{form}', EApprovalFormUpdateController::class)->name('api.tenant.v1.e_approval.forms.update');
    Route::delete('e-approval/forms/{form}', EApprovalFormDestroyController::class)->name('api.tenant.v1.e_approval.forms.destroy');
    Route::post('e-approval/forms/{form}/publish', EApprovalFormPublishController::class)->name('api.tenant.v1.e_approval.forms.publish');
    Route::get('e-approval/forms/{form}/public-links', EApprovalPublicFormLinkIndexController::class)->name('api.tenant.v1.e_approval.forms.public_links.index');
    Route::post('e-approval/forms/{form}/public-links', EApprovalPublicFormLinkStoreController::class)->name('api.tenant.v1.e_approval.forms.public_links.store');
    Route::post('e-approval/public-links/{publicLink}/revoke', EApprovalPublicFormLinkRevokeController::class)->name('api.tenant.v1.e_approval.public_links.revoke');
    Route::post('e-approval/public-links/{publicLink}/rotate', EApprovalPublicFormLinkRotateController::class)->name('api.tenant.v1.e_approval.public_links.rotate');
    Route::post('e-approval/forms/{form}/logo', EApprovalFormLogoStoreController::class)->name('api.tenant.v1.e_approval.forms.logo');
    Route::get('e-approval/forms/{form}/export', EApprovalFormExportController::class)->name('api.tenant.v1.e_approval.forms.export');
    Route::get('e-approval/pdf-layout/{formId}', EApprovalPdfLayoutShowController::class)->name('api.tenant.v1.e_approval.pdf_layout.show');
    Route::put('e-approval/pdf-layout/{formId}', EApprovalPdfLayoutUpdateController::class)->name('api.tenant.v1.e_approval.pdf_layout.update');
    Route::delete('e-approval/pdf-layout/{formId}', EApprovalPdfLayoutDestroyController::class)->name('api.tenant.v1.e_approval.pdf_layout.destroy');
    Route::get('e-approval/submissions', EApprovalSubmissionIndexController::class)->name('api.tenant.v1.e_approval.submissions.index');
    Route::post('e-approval/submissions', EApprovalSubmissionStoreController::class)->name('api.tenant.v1.e_approval.submissions.store');
    Route::get('e-approval/submissions/{submission}/print', EApprovalSubmissionPrintDataController::class)->name('api.tenant.v1.e_approval.submissions.print');
    Route::get('e-approval/submissions/{submission}', EApprovalSubmissionShowController::class)->name('api.tenant.v1.e_approval.submissions.show');
    Route::put('e-approval/submissions/{submission}/draft', EApprovalSubmissionDraftUpdateController::class)->name('api.tenant.v1.e_approval.submissions.draft.update');
    Route::post('e-approval/submissions/{submission}/submit', EApprovalSubmissionSubmitDraftController::class)->name('api.tenant.v1.e_approval.submissions.submit_draft');
    Route::post('e-approval/submissions/{submission}/cancel', EApprovalSubmissionCancelController::class)->name('api.tenant.v1.e_approval.submissions.cancel');
    Route::put('e-approval/submissions/{submission}/resubmit', EApprovalSubmissionResubmitController::class)->name('api.tenant.v1.e_approval.submissions.resubmit');
    Route::get('e-approval/submissions/{submission}/comments', EApprovalSubmissionCommentIndexController::class)->name('api.tenant.v1.e_approval.submissions.comments.index');
    Route::post('e-approval/submissions/{submission}/comments', EApprovalSubmissionCommentStoreController::class)->name('api.tenant.v1.e_approval.submissions.comments.store');
    Route::post('e-approval/submissions/{submission}/attachments', EApprovalSubmissionAttachmentStoreController::class)->name('api.tenant.v1.e_approval.submissions.attachments.store');
    Route::get('e-approval/attachments/{attachment}', EApprovalAttachmentDownloadController::class)->name('api.tenant.v1.e_approval.attachments.show');
    Route::get('e-approval/approvals', EApprovalApprovalIndexController::class)->name('api.tenant.v1.e_approval.approvals.index');
    Route::post('e-approval/approvals/{approval}/decide', EApprovalApprovalDecideController::class)->name('api.tenant.v1.e_approval.approvals.decide');
    Route::post('e-approval/approvals/{approval}/reroute', EApprovalApprovalRerouteController::class)->name('api.tenant.v1.e_approval.approvals.reroute');
    Route::get('e-approval/notifications', EApprovalNotificationIndexController::class)->name('api.tenant.v1.e_approval.notifications.index');
    Route::get('e-approval/notifications/unread-count', EApprovalNotificationUnreadCountController::class)->name('api.tenant.v1.e_approval.notifications.unread_count');
    Route::post('e-approval/notifications/mark-all-read', EApprovalNotificationMarkAllReadController::class)->name('api.tenant.v1.e_approval.notifications.mark_all_read');
    Route::post('e-approval/notifications/{notification}/read', EApprovalNotificationMarkReadController::class)->name('api.tenant.v1.e_approval.notifications.read');
    Route::get('e-approval/metadata', EApprovalMetadataController::class)->name('api.tenant.v1.e_approval.metadata');
    Route::get('e-approval/cash-advances/open', EApprovalCashAdvanceOpenController::class)->name('api.tenant.v1.e_approval.cash_advances.open');
    Route::get('e-approval/purchase-requisitions/open', EApprovalPurchaseRequisitionOpenController::class)->name('api.tenant.v1.e_approval.purchase_requisitions.open');
    Route::get('e-approval/settings', EApprovalSettingsShowController::class)->name('api.tenant.v1.e_approval.settings.show');
    Route::post('e-approval/settings/test-email', EApprovalSettingsTestEmailController::class)
        ->name('api.tenant.v1.e_approval.settings.test_email');
    Route::put('e-approval/settings', EApprovalSettingsUpdateController::class)->name('api.tenant.v1.e_approval.settings.update');
    Route::get('e-approval/settings/public', EApprovalSettingsPublicController::class)->name('api.tenant.v1.e_approval.settings.public');
    Route::get('e-approval/master-data/{key}', EApprovalMasterDataLookupController::class)->name('api.tenant.v1.e_approval.master_data.lookup');
    Route::get('e-approval/master-data-sets', EApprovalMasterDataSetIndexController::class)->name('api.tenant.v1.e_approval.master_data_sets.index');
    Route::post('e-approval/master-data-sets', EApprovalMasterDataSetStoreController::class)->name('api.tenant.v1.e_approval.master_data_sets.store');
    Route::put('e-approval/master-data-sets/{set}', EApprovalMasterDataSetUpdateController::class)->name('api.tenant.v1.e_approval.master_data_sets.update');
    Route::delete('e-approval/master-data-sets/{set}', EApprovalMasterDataSetDestroyController::class)->name('api.tenant.v1.e_approval.master_data_sets.destroy');
    Route::get('e-approval/master-data-sets/{set}/rows', EApprovalMasterDataRowIndexController::class)->name('api.tenant.v1.e_approval.master_data_rows.index');
    Route::post('e-approval/master-data-sets/{set}/rows', EApprovalMasterDataRowStoreController::class)->name('api.tenant.v1.e_approval.master_data_rows.store');
    Route::post('e-approval/master-data-sets/{set}/rows/bulk', EApprovalMasterDataRowBulkStoreController::class)->name('api.tenant.v1.e_approval.master_data_rows.bulk');
    Route::put('e-approval/master-data-rows/{row}', EApprovalMasterDataRowUpdateController::class)->name('api.tenant.v1.e_approval.master_data_rows.update');
    Route::delete('e-approval/master-data-rows/{row}', EApprovalMasterDataRowDestroyController::class)->name('api.tenant.v1.e_approval.master_data_rows.destroy');
    Route::get('e-approval/delegations', EApprovalDelegationIndexController::class)->name('api.tenant.v1.e_approval.delegations.index');
    Route::post('e-approval/delegations', EApprovalDelegationStoreController::class)->name('api.tenant.v1.e_approval.delegations.store');
    Route::delete('e-approval/delegations/{delegation}', EApprovalDelegationDestroyController::class)->name('api.tenant.v1.e_approval.delegations.destroy');
    Route::get('e-approval/me/profile', EApprovalMeProfileController::class)->name('api.tenant.v1.e_approval.me.profile');
    Route::put('e-approval/me/signature', EApprovalMeSignatureUpdateController::class)->name('api.tenant.v1.e_approval.me.signature');
    Route::post('e-approval/me/attachments', EApprovalMeAttachmentStoreController::class)->name('api.tenant.v1.e_approval.me.attachments.store');
    Route::delete('e-approval/me/attachments/{attachment}', EApprovalMeAttachmentDestroyController::class)->name('api.tenant.v1.e_approval.me.attachments.destroy');
    Route::post('e-approval/submissions/{submission}/revision', EApprovalSubmissionRevisionController::class)->name('api.tenant.v1.e_approval.submissions.revision');
    Route::put('e-approval/submissions/{submission}/dcf-resubmit', EApprovalSubmissionDcfResubmitController::class)->name('api.tenant.v1.e_approval.submissions.dcf_resubmit');
    Route::post('e-approval/submissions/{submission}/manual-follow-up', EApprovalSubmissionManualFollowUpController::class)->name('api.tenant.v1.e_approval.submissions.manual_follow_up');
    Route::post('e-approval/submissions/{submission}/document-links', EApprovalDocumentLinkStoreController::class)->name('api.tenant.v1.e_approval.document_links.store');
    Route::delete('e-approval/document-links/{link}', EApprovalDocumentLinkDestroyController::class)->name('api.tenant.v1.e_approval.document_links.destroy');
    Route::post('auth/mfa/recovery-codes/regenerate', [TenantAuthController::class, 'mfaRecoveryCodesRegenerate'])->name('api.tenant.v1.auth.mfa.recovery_codes.regenerate');

    Route::prefix('admin')->group(function () {
        Route::get('sso/config', [TenantSsoConfigController::class, 'show'])->name('api.tenant.v1.admin.sso.config.show');
        Route::put('sso/config', [TenantSsoConfigController::class, 'update'])->name('api.tenant.v1.admin.sso.config.update');
        Route::post('sso/test-connection', [TenantSsoConfigController::class, 'testConnection'])->name('api.tenant.v1.admin.sso.test');
        Route::get('users', TenantUserIndexController::class)->name('api.tenant.v1.admin.users.index');
        Route::get('users/export', TenantUserExportController::class)->name('api.tenant.v1.admin.users.export');
        Route::post('users', TenantUserStoreController::class)->name('api.tenant.v1.admin.users.store');
        Route::post('users/import', TenantUserImportController::class)->name('api.tenant.v1.admin.users.import');
        Route::patch('users/{user}', TenantUserUpdateController::class)->name('api.tenant.v1.admin.users.update');
        Route::post('users/{user}/impersonate', TenantUserImpersonateController::class)
            ->middleware('throttle:10,1')
            ->name('api.tenant.v1.admin.users.impersonate');
        Route::post('users/{user}/deactivate', TenantUserDeactivateController::class)->name('api.tenant.v1.admin.users.deactivate');
        Route::post('users/{user}/reactivate', TenantUserReactivateController::class)->name('api.tenant.v1.admin.users.reactivate');
        Route::delete('users/{user}', TenantUserDestroyController::class)->name('api.tenant.v1.admin.users.destroy');
        Route::get('roles', RoleIndexController::class)->name('api.tenant.v1.admin.roles.index');
        Route::post('roles', RoleStoreController::class)->name('api.tenant.v1.admin.roles.store');
        Route::patch('roles/{role}', RoleUpdateController::class)->name('api.tenant.v1.admin.roles.update');
        Route::get('billing', TenantBillingShowController::class)->name('api.tenant.v1.admin.billing.show');
        Route::get('billing/usage', TenantBillingUsageShowController::class)->name('api.tenant.v1.admin.billing.usage');
        Route::post('billing/checkout-session', TenantBillingCheckoutSessionStoreController::class)
            ->middleware('throttle:20,1')
            ->name('api.tenant.v1.admin.billing.checkout');
        Route::post('billing/portal-session', TenantBillingPortalSessionStoreController::class)
            ->middleware('throttle:20,1')
            ->name('api.tenant.v1.admin.billing.portal');
        Route::get('settings', AdminSettingsShowController::class)->name('api.tenant.v1.admin.settings.show');
        Route::patch('settings', AdminSettingsUpdateController::class)->name('api.tenant.v1.admin.settings.update');
    });
});

Route::middleware(['tenant.sanctum', 'auth:sanctum', 'auth.session'])->group(function () {
    Route::post('auth/mfa/enroll/start', [TenantAuthController::class, 'mfaEnrollStart'])->name('api.tenant.v1.auth.mfa.enroll.start');
    Route::post('auth/mfa/enroll/complete', [TenantAuthController::class, 'mfaEnrollComplete'])->name('api.tenant.v1.auth.mfa.enroll.complete');
});
