import type { AuthUser } from "@/types/auth";

export const permissions = {
  dashboardView: "dashboard:view",
  workspaceAuditView: "workspace:audit:view",
  workspaceEnvironmentsSwitch: "workspace:environments:switch",
  gisView: "gis:view",
  sitesView: "sites:view",
  tenantManage: "tenant:manage",
  billingView: "billing:view",
  billingManage: "billing:manage",
  userManage: "user:manage",
  userImpersonate: "user:impersonate",
  roleManage: "role:manage",
  projectOneView: "project_one:view",
  projectOneManage: "project_one:manage",
  rolloutView: "project_one:rollout:view",
  rolloutManage: "project_one:rollout:manage",
  rolloutGateApprove: "project_one:rollout:gate:approve",
  saqManage: "project_one:saq:manage",
  cmeManage: "project_one:cme:manage",
  financeView: "project_one:finance:view",
  financeEdit: "project_one:finance:edit",
  financeViewDiscipline: "project_one:finance:view_discipline",
  playbookConfigure: "project_one:playbook:configure",
  towerOneView: "tower_one:view",
  fiberOneView: "fiber_one:view",
  assetOneView: "asset_one:view",
  eApprovalView: "e_approval:view",
  eApprovalFormsManage: "e_approval:forms:manage",
  eApprovalSubmissionsCreate: "e_approval:submissions:create",
  eApprovalSubmissionsView: "e_approval:submissions:view",
  eApprovalApprove: "e_approval:approve",
  eApprovalAuditView: "e_approval:audit:view",
  eApprovalSettingsManage: "e_approval:settings:manage",
  ticketingView: "ticketing:view",
  ticketingTicketsCreate: "ticketing:tickets:create",
  ticketingTicketsManage: "ticketing:tickets:manage",
  ticketingSettingsManage: "ticketing:settings:manage",
  procurementOneView: "procurement_one:view",
  procurementOneDocumentsCreate: "procurement_one:documents:create",
  procurementOneDocumentsManage: "procurement_one:documents:manage",
  procurementOneSettingsManage: "procurement_one:settings:manage",
  procurementOneVendorsView: "procurement_one:vendors:view",
  procurementOneVendorsManage: "procurement_one:vendors:manage",
  procurementOneInventoryView: "procurement_one:inventory:view",
  procurementOneInventoryManage: "procurement_one:inventory:manage",
  financeOneView: "finance_one:view",
  financeOneDocumentsCreate: "finance_one:documents:create",
  financeOneDocumentsManage: "finance_one:documents:manage",
  financeOneBudgetManage: "finance_one:budget:manage",
  financeOneContractsManage: "finance_one:contracts:manage",
  financeOnePaymentsManage: "finance_one:payments:manage",
  financeOneReportsView: "finance_one:reports:view",
  financeOneSettingsManage: "finance_one:settings:manage",
  assetOneAssetsManage: "asset_one:assets:manage",
  documentsView: "documents:view",
  documentsUpload: "documents:upload",
  documentsManage: "documents:manage",
  documentsTemplateManage: "documents:template:manage",
  documentsControlledView: "documents:controlled:view",
  documentsControlledCreate: "documents:controlled:create",
  documentsControlledApprove: "documents:controlled:approve",
  documentsControlledManage: "documents:controlled:manage",
  documentsControlledImport: "documents:controlled:import",
  aiAssistantUse: "ai_assistant:use",
  aiAssistantToolsUse: "ai_assistant:tools:use",
  aiAssistantActionsExecute: "ai_assistant:actions:execute",
  aiAssistantKnowledgeManage: "ai_assistant:knowledge:manage",
  aiAssistantConversationsAudit: "ai_assistant:conversations:audit",
} as const;

export function hasPermission(
  user: AuthUser | null,
  requiredPermissions: string[] = [],
): boolean {
  if (!user) return false;
  if (requiredPermissions.length === 0) return true;

  return requiredPermissions.every((permission) =>
    user.permissions.includes(permission),
  );
}
